/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.training.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nexcent.training.model.ArticleImportState;
import com.nexcent.training.model.ArticleImportStateModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ArticleImportState service. Represents a row in the &quot;NXC_ArticleImportState&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ArticleImportStateModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArticleImportStateImpl}.
 * </p>
 *
 * @author Nexcent Training
 * @see ArticleImportStateImpl
 * @generated
 */
public class ArticleImportStateModelImpl
	extends BaseModelImpl<ArticleImportState>
	implements ArticleImportStateModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a article import state model instance should use the <code>ArticleImportState</code> interface instead.
	 */
	public static final String TABLE_NAME = "NXC_ArticleImportState";

	public static final Object[][] TABLE_COLUMNS = {
		{"articleImportStateId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"articleERC", Types.VARCHAR},
		{"locale", Types.VARCHAR}, {"payloadHash", Types.VARCHAR},
		{"lastImportJobId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("articleImportStateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("articleERC", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("locale", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("payloadHash", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastImportJobId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NXC_ArticleImportState (articleImportStateId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,articleERC VARCHAR(75) null,locale VARCHAR(75) null,payloadHash VARCHAR(75) null,lastImportJobId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table NXC_ArticleImportState";

	public static final String ORDER_BY_JPQL =
		" ORDER BY articleImportState.articleImportStateId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NXC_ArticleImportState.articleImportStateId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ARTICLEERC_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCALE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ARTICLEIMPORTSTATEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ArticleImportStateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _articleImportStateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setArticleImportStateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _articleImportStateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ArticleImportState.class;
	}

	@Override
	public String getModelClassName() {
		return ArticleImportState.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ArticleImportState, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ArticleImportState, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArticleImportState, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ArticleImportState)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ArticleImportState, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ArticleImportState, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ArticleImportState)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ArticleImportState, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ArticleImportState, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ArticleImportState, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ArticleImportState, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ArticleImportState, Object>>();

			attributeGetterFunctions.put(
				"articleImportStateId",
				ArticleImportState::getArticleImportStateId);
			attributeGetterFunctions.put(
				"groupId", ArticleImportState::getGroupId);
			attributeGetterFunctions.put(
				"companyId", ArticleImportState::getCompanyId);
			attributeGetterFunctions.put(
				"createDate", ArticleImportState::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ArticleImportState::getModifiedDate);
			attributeGetterFunctions.put(
				"articleERC", ArticleImportState::getArticleERC);
			attributeGetterFunctions.put(
				"locale", ArticleImportState::getLocale);
			attributeGetterFunctions.put(
				"payloadHash", ArticleImportState::getPayloadHash);
			attributeGetterFunctions.put(
				"lastImportJobId", ArticleImportState::getLastImportJobId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ArticleImportState, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ArticleImportState, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ArticleImportState, ?>>();

			attributeSetterBiConsumers.put(
				"articleImportStateId",
				(BiConsumer<ArticleImportState, Long>)
					ArticleImportState::setArticleImportStateId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ArticleImportState, Long>)
					ArticleImportState::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ArticleImportState, Long>)
					ArticleImportState::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ArticleImportState, Date>)
					ArticleImportState::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ArticleImportState, Date>)
					ArticleImportState::setModifiedDate);
			attributeSetterBiConsumers.put(
				"articleERC",
				(BiConsumer<ArticleImportState, String>)
					ArticleImportState::setArticleERC);
			attributeSetterBiConsumers.put(
				"locale",
				(BiConsumer<ArticleImportState, String>)
					ArticleImportState::setLocale);
			attributeSetterBiConsumers.put(
				"payloadHash",
				(BiConsumer<ArticleImportState, String>)
					ArticleImportState::setPayloadHash);
			attributeSetterBiConsumers.put(
				"lastImportJobId",
				(BiConsumer<ArticleImportState, Long>)
					ArticleImportState::setLastImportJobId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getArticleImportStateId() {
		return _articleImportStateId;
	}

	@Override
	public void setArticleImportStateId(long articleImportStateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_articleImportStateId = articleImportStateId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getArticleERC() {
		if (_articleERC == null) {
			return "";
		}
		else {
			return _articleERC;
		}
	}

	@Override
	public void setArticleERC(String articleERC) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_articleERC = articleERC;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalArticleERC() {
		return getColumnOriginalValue("articleERC");
	}

	@Override
	public String getLocale() {
		if (_locale == null) {
			return "";
		}
		else {
			return _locale;
		}
	}

	@Override
	public void setLocale(String locale) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locale = locale;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLocale() {
		return getColumnOriginalValue("locale");
	}

	@Override
	public String getPayloadHash() {
		if (_payloadHash == null) {
			return "";
		}
		else {
			return _payloadHash;
		}
	}

	@Override
	public void setPayloadHash(String payloadHash) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_payloadHash = payloadHash;
	}

	@Override
	public long getLastImportJobId() {
		return _lastImportJobId;
	}

	@Override
	public void setLastImportJobId(long lastImportJobId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastImportJobId = lastImportJobId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ArticleImportState.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ArticleImportState toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ArticleImportState>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ArticleImportStateImpl articleImportStateImpl =
			new ArticleImportStateImpl();

		articleImportStateImpl.setArticleImportStateId(
			getArticleImportStateId());
		articleImportStateImpl.setGroupId(getGroupId());
		articleImportStateImpl.setCompanyId(getCompanyId());
		articleImportStateImpl.setCreateDate(getCreateDate());
		articleImportStateImpl.setModifiedDate(getModifiedDate());
		articleImportStateImpl.setArticleERC(getArticleERC());
		articleImportStateImpl.setLocale(getLocale());
		articleImportStateImpl.setPayloadHash(getPayloadHash());
		articleImportStateImpl.setLastImportJobId(getLastImportJobId());

		articleImportStateImpl.resetOriginalValues();

		return articleImportStateImpl;
	}

	@Override
	public ArticleImportState cloneWithOriginalValues() {
		ArticleImportStateImpl articleImportStateImpl =
			new ArticleImportStateImpl();

		articleImportStateImpl.setArticleImportStateId(
			this.<Long>getColumnOriginalValue("articleImportStateId"));
		articleImportStateImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		articleImportStateImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		articleImportStateImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		articleImportStateImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		articleImportStateImpl.setArticleERC(
			this.<String>getColumnOriginalValue("articleERC"));
		articleImportStateImpl.setLocale(
			this.<String>getColumnOriginalValue("locale"));
		articleImportStateImpl.setPayloadHash(
			this.<String>getColumnOriginalValue("payloadHash"));
		articleImportStateImpl.setLastImportJobId(
			this.<Long>getColumnOriginalValue("lastImportJobId"));

		return articleImportStateImpl;
	}

	@Override
	public int compareTo(ArticleImportState articleImportState) {
		long primaryKey = articleImportState.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ArticleImportState)) {
			return false;
		}

		ArticleImportState articleImportState = (ArticleImportState)object;

		long primaryKey = articleImportState.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ArticleImportState> toCacheModel() {
		ArticleImportStateCacheModel articleImportStateCacheModel =
			new ArticleImportStateCacheModel();

		articleImportStateCacheModel.articleImportStateId =
			getArticleImportStateId();

		articleImportStateCacheModel.groupId = getGroupId();

		articleImportStateCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			articleImportStateCacheModel.createDate = createDate.getTime();
		}
		else {
			articleImportStateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			articleImportStateCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			articleImportStateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		articleImportStateCacheModel.articleERC = getArticleERC();

		String articleERC = articleImportStateCacheModel.articleERC;

		if ((articleERC != null) && (articleERC.length() == 0)) {
			articleImportStateCacheModel.articleERC = null;
		}

		articleImportStateCacheModel.locale = getLocale();

		String locale = articleImportStateCacheModel.locale;

		if ((locale != null) && (locale.length() == 0)) {
			articleImportStateCacheModel.locale = null;
		}

		articleImportStateCacheModel.payloadHash = getPayloadHash();

		String payloadHash = articleImportStateCacheModel.payloadHash;

		if ((payloadHash != null) && (payloadHash.length() == 0)) {
			articleImportStateCacheModel.payloadHash = null;
		}

		articleImportStateCacheModel.lastImportJobId = getLastImportJobId();

		return articleImportStateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ArticleImportState, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ArticleImportState, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArticleImportState, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ArticleImportState)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ArticleImportState>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ArticleImportState.class, ModelWrapper.class);

	}

	private long _articleImportStateId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _articleERC;
	private String _locale;
	private String _payloadHash;
	private long _lastImportJobId;

	public <T> T getColumnValue(String columnName) {
		Function<ArticleImportState, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ArticleImportState)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"articleImportStateId", _articleImportStateId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("articleERC", _articleERC);
		_columnOriginalValues.put("locale", _locale);
		_columnOriginalValues.put("payloadHash", _payloadHash);
		_columnOriginalValues.put("lastImportJobId", _lastImportJobId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("articleImportStateId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("articleERC", 32L);

		columnBitmasks.put("locale", 64L);

		columnBitmasks.put("payloadHash", 128L);

		columnBitmasks.put("lastImportJobId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ArticleImportState _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:975624151