/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.training.model.impl;

import com.nexcent.training.model.ArticleImportState;
import com.nexcent.training.service.ArticleImportStateLocalServiceUtil;

/**
 * The extended model base implementation for the ArticleImportState service. Represents a row in the &quot;NXC_ArticleImportState&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArticleImportStateImpl}.
 * </p>
 *
 * @author Nexcent Training
 * @see ArticleImportStateImpl
 * @see ArticleImportState
 * @generated
 */
public abstract class ArticleImportStateBaseImpl
	extends ArticleImportStateModelImpl implements ArticleImportState {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a article import state model instance should use the <code>ArticleImportState</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ArticleImportStateLocalServiceUtil.addArticleImportState(this);
		}
		else {
			ArticleImportStateLocalServiceUtil.updateArticleImportState(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:701000490