/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.training.model.impl;

import com.nexcent.training.model.ImportJob;
import com.nexcent.training.service.ImportJobLocalServiceUtil;

/**
 * The extended model base implementation for the ImportJob service. Represents a row in the &quot;NXC_ImportJob&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImportJobImpl}.
 * </p>
 *
 * @author Nexcent Training
 * @see ImportJobImpl
 * @see ImportJob
 * @generated
 */
public abstract class ImportJobBaseImpl
	extends ImportJobModelImpl implements ImportJob {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a import job model instance should use the <code>ImportJob</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ImportJobLocalServiceUtil.addImportJob(this);
		}
		else {
			ImportJobLocalServiceUtil.updateImportJob(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-622576892