/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.training.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nexcent.training.model.ImportJob;
import com.nexcent.training.model.ImportJobModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ImportJob service. Represents a row in the &quot;NXC_ImportJob&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ImportJobModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImportJobImpl}.
 * </p>
 *
 * @author Nexcent Training
 * @see ImportJobImpl
 * @generated
 */
public class ImportJobModelImpl
	extends BaseModelImpl<ImportJob> implements ImportJobModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a import job model instance should use the <code>ImportJob</code> interface instead.
	 */
	public static final String TABLE_NAME = "NXC_ImportJob";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"importJobId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"jobKey", Types.VARCHAR}, {"fileEntryId", Types.BIGINT},
		{"fileName", Types.VARCHAR}, {"sha256", Types.VARCHAR},
		{"importProfileKey", Types.VARCHAR},
		{"packageSchemaVersion", Types.VARCHAR},
		{"structureERC", Types.VARCHAR}, {"status", Types.VARCHAR},
		{"totalRows", Types.INTEGER}, {"createdRows", Types.INTEGER},
		{"updatedRows", Types.INTEGER}, {"skippedRows", Types.INTEGER},
		{"failedRows", Types.INTEGER}, {"startedDate", Types.TIMESTAMP},
		{"completedDate", Types.TIMESTAMP}, {"errorMessage", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("importJobId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("jobKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sha256", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("importProfileKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("packageSchemaVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("structureERC", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("totalRows", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("createdRows", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("updatedRows", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("skippedRows", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("failedRows", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("startedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("completedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("errorMessage", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NXC_ImportJob (uuid_ VARCHAR(75) null,importJobId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,jobKey VARCHAR(75) null,fileEntryId LONG,fileName VARCHAR(75) null,sha256 VARCHAR(75) null,importProfileKey VARCHAR(75) null,packageSchemaVersion VARCHAR(75) null,structureERC VARCHAR(75) null,status VARCHAR(75) null,totalRows INTEGER,createdRows INTEGER,updatedRows INTEGER,skippedRows INTEGER,failedRows INTEGER,startedDate DATE null,completedDate DATE null,errorMessage VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table NXC_ImportJob";

	public static final String ORDER_BY_JPQL =
		" ORDER BY importJob.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NXC_ImportJob.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long JOBKEY_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ImportJobModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _importJobId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setImportJobId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _importJobId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ImportJob.class;
	}

	@Override
	public String getModelClassName() {
		return ImportJob.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ImportJob, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ImportJob, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ImportJob, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ImportJob)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ImportJob, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ImportJob, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ImportJob)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ImportJob, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ImportJob, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ImportJob, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ImportJob, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<ImportJob, Object>>();

			attributeGetterFunctions.put("uuid", ImportJob::getUuid);
			attributeGetterFunctions.put(
				"importJobId", ImportJob::getImportJobId);
			attributeGetterFunctions.put("groupId", ImportJob::getGroupId);
			attributeGetterFunctions.put("companyId", ImportJob::getCompanyId);
			attributeGetterFunctions.put("userId", ImportJob::getUserId);
			attributeGetterFunctions.put("userName", ImportJob::getUserName);
			attributeGetterFunctions.put(
				"createDate", ImportJob::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ImportJob::getModifiedDate);
			attributeGetterFunctions.put("jobKey", ImportJob::getJobKey);
			attributeGetterFunctions.put(
				"fileEntryId", ImportJob::getFileEntryId);
			attributeGetterFunctions.put("fileName", ImportJob::getFileName);
			attributeGetterFunctions.put("sha256", ImportJob::getSha256);
			attributeGetterFunctions.put(
				"importProfileKey", ImportJob::getImportProfileKey);
			attributeGetterFunctions.put(
				"packageSchemaVersion", ImportJob::getPackageSchemaVersion);
			attributeGetterFunctions.put(
				"structureERC", ImportJob::getStructureERC);
			attributeGetterFunctions.put("status", ImportJob::getStatus);
			attributeGetterFunctions.put("totalRows", ImportJob::getTotalRows);
			attributeGetterFunctions.put(
				"createdRows", ImportJob::getCreatedRows);
			attributeGetterFunctions.put(
				"updatedRows", ImportJob::getUpdatedRows);
			attributeGetterFunctions.put(
				"skippedRows", ImportJob::getSkippedRows);
			attributeGetterFunctions.put(
				"failedRows", ImportJob::getFailedRows);
			attributeGetterFunctions.put(
				"startedDate", ImportJob::getStartedDate);
			attributeGetterFunctions.put(
				"completedDate", ImportJob::getCompletedDate);
			attributeGetterFunctions.put(
				"errorMessage", ImportJob::getErrorMessage);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ImportJob, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ImportJob, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ImportJob, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<ImportJob, String>)ImportJob::setUuid);
			attributeSetterBiConsumers.put(
				"importJobId",
				(BiConsumer<ImportJob, Long>)ImportJob::setImportJobId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<ImportJob, Long>)ImportJob::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ImportJob, Long>)ImportJob::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<ImportJob, Long>)ImportJob::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<ImportJob, String>)ImportJob::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ImportJob, Date>)ImportJob::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ImportJob, Date>)ImportJob::setModifiedDate);
			attributeSetterBiConsumers.put(
				"jobKey", (BiConsumer<ImportJob, String>)ImportJob::setJobKey);
			attributeSetterBiConsumers.put(
				"fileEntryId",
				(BiConsumer<ImportJob, Long>)ImportJob::setFileEntryId);
			attributeSetterBiConsumers.put(
				"fileName",
				(BiConsumer<ImportJob, String>)ImportJob::setFileName);
			attributeSetterBiConsumers.put(
				"sha256", (BiConsumer<ImportJob, String>)ImportJob::setSha256);
			attributeSetterBiConsumers.put(
				"importProfileKey",
				(BiConsumer<ImportJob, String>)ImportJob::setImportProfileKey);
			attributeSetterBiConsumers.put(
				"packageSchemaVersion",
				(BiConsumer<ImportJob, String>)
					ImportJob::setPackageSchemaVersion);
			attributeSetterBiConsumers.put(
				"structureERC",
				(BiConsumer<ImportJob, String>)ImportJob::setStructureERC);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<ImportJob, String>)ImportJob::setStatus);
			attributeSetterBiConsumers.put(
				"totalRows",
				(BiConsumer<ImportJob, Integer>)ImportJob::setTotalRows);
			attributeSetterBiConsumers.put(
				"createdRows",
				(BiConsumer<ImportJob, Integer>)ImportJob::setCreatedRows);
			attributeSetterBiConsumers.put(
				"updatedRows",
				(BiConsumer<ImportJob, Integer>)ImportJob::setUpdatedRows);
			attributeSetterBiConsumers.put(
				"skippedRows",
				(BiConsumer<ImportJob, Integer>)ImportJob::setSkippedRows);
			attributeSetterBiConsumers.put(
				"failedRows",
				(BiConsumer<ImportJob, Integer>)ImportJob::setFailedRows);
			attributeSetterBiConsumers.put(
				"startedDate",
				(BiConsumer<ImportJob, Date>)ImportJob::setStartedDate);
			attributeSetterBiConsumers.put(
				"completedDate",
				(BiConsumer<ImportJob, Date>)ImportJob::setCompletedDate);
			attributeSetterBiConsumers.put(
				"errorMessage",
				(BiConsumer<ImportJob, String>)ImportJob::setErrorMessage);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getImportJobId() {
		return _importJobId;
	}

	@Override
	public void setImportJobId(long importJobId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importJobId = importJobId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getJobKey() {
		if (_jobKey == null) {
			return "";
		}
		else {
			return _jobKey;
		}
	}

	@Override
	public void setJobKey(String jobKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jobKey = jobKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalJobKey() {
		return getColumnOriginalValue("jobKey");
	}

	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileName = fileName;
	}

	@Override
	public String getSha256() {
		if (_sha256 == null) {
			return "";
		}
		else {
			return _sha256;
		}
	}

	@Override
	public void setSha256(String sha256) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sha256 = sha256;
	}

	@Override
	public String getImportProfileKey() {
		if (_importProfileKey == null) {
			return "";
		}
		else {
			return _importProfileKey;
		}
	}

	@Override
	public void setImportProfileKey(String importProfileKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importProfileKey = importProfileKey;
	}

	@Override
	public String getPackageSchemaVersion() {
		if (_packageSchemaVersion == null) {
			return "";
		}
		else {
			return _packageSchemaVersion;
		}
	}

	@Override
	public void setPackageSchemaVersion(String packageSchemaVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_packageSchemaVersion = packageSchemaVersion;
	}

	@Override
	public String getStructureERC() {
		if (_structureERC == null) {
			return "";
		}
		else {
			return _structureERC;
		}
	}

	@Override
	public void setStructureERC(String structureERC) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_structureERC = structureERC;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	@Override
	public int getTotalRows() {
		return _totalRows;
	}

	@Override
	public void setTotalRows(int totalRows) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_totalRows = totalRows;
	}

	@Override
	public int getCreatedRows() {
		return _createdRows;
	}

	@Override
	public void setCreatedRows(int createdRows) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdRows = createdRows;
	}

	@Override
	public int getUpdatedRows() {
		return _updatedRows;
	}

	@Override
	public void setUpdatedRows(int updatedRows) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedRows = updatedRows;
	}

	@Override
	public int getSkippedRows() {
		return _skippedRows;
	}

	@Override
	public void setSkippedRows(int skippedRows) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_skippedRows = skippedRows;
	}

	@Override
	public int getFailedRows() {
		return _failedRows;
	}

	@Override
	public void setFailedRows(int failedRows) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_failedRows = failedRows;
	}

	@Override
	public Date getStartedDate() {
		return _startedDate;
	}

	@Override
	public void setStartedDate(Date startedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startedDate = startedDate;
	}

	@Override
	public Date getCompletedDate() {
		return _completedDate;
	}

	@Override
	public void setCompletedDate(Date completedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_completedDate = completedDate;
	}

	@Override
	public String getErrorMessage() {
		if (_errorMessage == null) {
			return "";
		}
		else {
			return _errorMessage;
		}
	}

	@Override
	public void setErrorMessage(String errorMessage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_errorMessage = errorMessage;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ImportJob.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ImportJob.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ImportJob toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ImportJob>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ImportJobImpl importJobImpl = new ImportJobImpl();

		importJobImpl.setUuid(getUuid());
		importJobImpl.setImportJobId(getImportJobId());
		importJobImpl.setGroupId(getGroupId());
		importJobImpl.setCompanyId(getCompanyId());
		importJobImpl.setUserId(getUserId());
		importJobImpl.setUserName(getUserName());
		importJobImpl.setCreateDate(getCreateDate());
		importJobImpl.setModifiedDate(getModifiedDate());
		importJobImpl.setJobKey(getJobKey());
		importJobImpl.setFileEntryId(getFileEntryId());
		importJobImpl.setFileName(getFileName());
		importJobImpl.setSha256(getSha256());
		importJobImpl.setImportProfileKey(getImportProfileKey());
		importJobImpl.setPackageSchemaVersion(getPackageSchemaVersion());
		importJobImpl.setStructureERC(getStructureERC());
		importJobImpl.setStatus(getStatus());
		importJobImpl.setTotalRows(getTotalRows());
		importJobImpl.setCreatedRows(getCreatedRows());
		importJobImpl.setUpdatedRows(getUpdatedRows());
		importJobImpl.setSkippedRows(getSkippedRows());
		importJobImpl.setFailedRows(getFailedRows());
		importJobImpl.setStartedDate(getStartedDate());
		importJobImpl.setCompletedDate(getCompletedDate());
		importJobImpl.setErrorMessage(getErrorMessage());

		importJobImpl.resetOriginalValues();

		return importJobImpl;
	}

	@Override
	public ImportJob cloneWithOriginalValues() {
		ImportJobImpl importJobImpl = new ImportJobImpl();

		importJobImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		importJobImpl.setImportJobId(
			this.<Long>getColumnOriginalValue("importJobId"));
		importJobImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		importJobImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		importJobImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		importJobImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		importJobImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		importJobImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		importJobImpl.setJobKey(this.<String>getColumnOriginalValue("jobKey"));
		importJobImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		importJobImpl.setFileName(
			this.<String>getColumnOriginalValue("fileName"));
		importJobImpl.setSha256(this.<String>getColumnOriginalValue("sha256"));
		importJobImpl.setImportProfileKey(
			this.<String>getColumnOriginalValue("importProfileKey"));
		importJobImpl.setPackageSchemaVersion(
			this.<String>getColumnOriginalValue("packageSchemaVersion"));
		importJobImpl.setStructureERC(
			this.<String>getColumnOriginalValue("structureERC"));
		importJobImpl.setStatus(this.<String>getColumnOriginalValue("status"));
		importJobImpl.setTotalRows(
			this.<Integer>getColumnOriginalValue("totalRows"));
		importJobImpl.setCreatedRows(
			this.<Integer>getColumnOriginalValue("createdRows"));
		importJobImpl.setUpdatedRows(
			this.<Integer>getColumnOriginalValue("updatedRows"));
		importJobImpl.setSkippedRows(
			this.<Integer>getColumnOriginalValue("skippedRows"));
		importJobImpl.setFailedRows(
			this.<Integer>getColumnOriginalValue("failedRows"));
		importJobImpl.setStartedDate(
			this.<Date>getColumnOriginalValue("startedDate"));
		importJobImpl.setCompletedDate(
			this.<Date>getColumnOriginalValue("completedDate"));
		importJobImpl.setErrorMessage(
			this.<String>getColumnOriginalValue("errorMessage"));

		return importJobImpl;
	}

	@Override
	public int compareTo(ImportJob importJob) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), importJob.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ImportJob)) {
			return false;
		}

		ImportJob importJob = (ImportJob)object;

		long primaryKey = importJob.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ImportJob> toCacheModel() {
		ImportJobCacheModel importJobCacheModel = new ImportJobCacheModel();

		importJobCacheModel.uuid = getUuid();

		String uuid = importJobCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			importJobCacheModel.uuid = null;
		}

		importJobCacheModel.importJobId = getImportJobId();

		importJobCacheModel.groupId = getGroupId();

		importJobCacheModel.companyId = getCompanyId();

		importJobCacheModel.userId = getUserId();

		importJobCacheModel.userName = getUserName();

		String userName = importJobCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			importJobCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			importJobCacheModel.createDate = createDate.getTime();
		}
		else {
			importJobCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			importJobCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			importJobCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		importJobCacheModel.jobKey = getJobKey();

		String jobKey = importJobCacheModel.jobKey;

		if ((jobKey != null) && (jobKey.length() == 0)) {
			importJobCacheModel.jobKey = null;
		}

		importJobCacheModel.fileEntryId = getFileEntryId();

		importJobCacheModel.fileName = getFileName();

		String fileName = importJobCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			importJobCacheModel.fileName = null;
		}

		importJobCacheModel.sha256 = getSha256();

		String sha256 = importJobCacheModel.sha256;

		if ((sha256 != null) && (sha256.length() == 0)) {
			importJobCacheModel.sha256 = null;
		}

		importJobCacheModel.importProfileKey = getImportProfileKey();

		String importProfileKey = importJobCacheModel.importProfileKey;

		if ((importProfileKey != null) && (importProfileKey.length() == 0)) {
			importJobCacheModel.importProfileKey = null;
		}

		importJobCacheModel.packageSchemaVersion = getPackageSchemaVersion();

		String packageSchemaVersion = importJobCacheModel.packageSchemaVersion;

		if ((packageSchemaVersion != null) &&
			(packageSchemaVersion.length() == 0)) {

			importJobCacheModel.packageSchemaVersion = null;
		}

		importJobCacheModel.structureERC = getStructureERC();

		String structureERC = importJobCacheModel.structureERC;

		if ((structureERC != null) && (structureERC.length() == 0)) {
			importJobCacheModel.structureERC = null;
		}

		importJobCacheModel.status = getStatus();

		String status = importJobCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			importJobCacheModel.status = null;
		}

		importJobCacheModel.totalRows = getTotalRows();

		importJobCacheModel.createdRows = getCreatedRows();

		importJobCacheModel.updatedRows = getUpdatedRows();

		importJobCacheModel.skippedRows = getSkippedRows();

		importJobCacheModel.failedRows = getFailedRows();

		Date startedDate = getStartedDate();

		if (startedDate != null) {
			importJobCacheModel.startedDate = startedDate.getTime();
		}
		else {
			importJobCacheModel.startedDate = Long.MIN_VALUE;
		}

		Date completedDate = getCompletedDate();

		if (completedDate != null) {
			importJobCacheModel.completedDate = completedDate.getTime();
		}
		else {
			importJobCacheModel.completedDate = Long.MIN_VALUE;
		}

		importJobCacheModel.errorMessage = getErrorMessage();

		String errorMessage = importJobCacheModel.errorMessage;

		if ((errorMessage != null) && (errorMessage.length() == 0)) {
			importJobCacheModel.errorMessage = null;
		}

		return importJobCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ImportJob, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ImportJob, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ImportJob, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ImportJob)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ImportJob>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ImportJob.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _importJobId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _jobKey;
	private long _fileEntryId;
	private String _fileName;
	private String _sha256;
	private String _importProfileKey;
	private String _packageSchemaVersion;
	private String _structureERC;
	private String _status;
	private int _totalRows;
	private int _createdRows;
	private int _updatedRows;
	private int _skippedRows;
	private int _failedRows;
	private Date _startedDate;
	private Date _completedDate;
	private String _errorMessage;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ImportJob, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ImportJob)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("importJobId", _importJobId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("jobKey", _jobKey);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("fileName", _fileName);
		_columnOriginalValues.put("sha256", _sha256);
		_columnOriginalValues.put("importProfileKey", _importProfileKey);
		_columnOriginalValues.put(
			"packageSchemaVersion", _packageSchemaVersion);
		_columnOriginalValues.put("structureERC", _structureERC);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("totalRows", _totalRows);
		_columnOriginalValues.put("createdRows", _createdRows);
		_columnOriginalValues.put("updatedRows", _updatedRows);
		_columnOriginalValues.put("skippedRows", _skippedRows);
		_columnOriginalValues.put("failedRows", _failedRows);
		_columnOriginalValues.put("startedDate", _startedDate);
		_columnOriginalValues.put("completedDate", _completedDate);
		_columnOriginalValues.put("errorMessage", _errorMessage);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("importJobId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("jobKey", 256L);

		columnBitmasks.put("fileEntryId", 512L);

		columnBitmasks.put("fileName", 1024L);

		columnBitmasks.put("sha256", 2048L);

		columnBitmasks.put("importProfileKey", 4096L);

		columnBitmasks.put("packageSchemaVersion", 8192L);

		columnBitmasks.put("structureERC", 16384L);

		columnBitmasks.put("status", 32768L);

		columnBitmasks.put("totalRows", 65536L);

		columnBitmasks.put("createdRows", 131072L);

		columnBitmasks.put("updatedRows", 262144L);

		columnBitmasks.put("skippedRows", 524288L);

		columnBitmasks.put("failedRows", 1048576L);

		columnBitmasks.put("startedDate", 2097152L);

		columnBitmasks.put("completedDate", 4194304L);

		columnBitmasks.put("errorMessage", 8388608L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ImportJob _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1706286437