/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.training.model.impl;

import com.nexcent.training.model.ImportJobItem;
import com.nexcent.training.service.ImportJobItemLocalServiceUtil;

/**
 * The extended model base implementation for the ImportJobItem service. Represents a row in the &quot;NXC_ImportJobItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImportJobItemImpl}.
 * </p>
 *
 * @author Nexcent Training
 * @see ImportJobItemImpl
 * @see ImportJobItem
 * @generated
 */
public abstract class ImportJobItemBaseImpl
	extends ImportJobItemModelImpl implements ImportJobItem {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a import job item model instance should use the <code>ImportJobItem</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ImportJobItemLocalServiceUtil.addImportJobItem(this);
		}
		else {
			ImportJobItemLocalServiceUtil.updateImportJobItem(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1168699732