/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.training.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nexcent.training.model.ImportJobItem;
import com.nexcent.training.model.ImportJobItemModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ImportJobItem service. Represents a row in the &quot;NXC_ImportJobItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ImportJobItemModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImportJobItemImpl}.
 * </p>
 *
 * @author Nexcent Training
 * @see ImportJobItemImpl
 * @generated
 */
public class ImportJobItemModelImpl
	extends BaseModelImpl<ImportJobItem> implements ImportJobItemModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a import job item model instance should use the <code>ImportJobItem</code> interface instead.
	 */
	public static final String TABLE_NAME = "NXC_ImportJobItem";

	public static final Object[][] TABLE_COLUMNS = {
		{"importJobItemId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"importJobId", Types.BIGINT},
		{"rowNumber", Types.INTEGER}, {"articleERC", Types.VARCHAR},
		{"locale", Types.VARCHAR}, {"operation", Types.VARCHAR},
		{"result", Types.VARCHAR}, {"severity", Types.VARCHAR},
		{"messageCode", Types.VARCHAR}, {"message", Types.VARCHAR},
		{"payloadHash", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("importJobItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("importJobId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("rowNumber", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("articleERC", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("locale", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("operation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("result", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("severity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("messageCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("message", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("payloadHash", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NXC_ImportJobItem (importJobItemId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,importJobId LONG,rowNumber INTEGER,articleERC VARCHAR(75) null,locale VARCHAR(75) null,operation VARCHAR(75) null,result VARCHAR(75) null,severity VARCHAR(75) null,messageCode VARCHAR(75) null,message VARCHAR(75) null,payloadHash VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table NXC_ImportJobItem";

	public static final String ORDER_BY_JPQL =
		" ORDER BY importJobItem.rowNumber ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NXC_ImportJobItem.rowNumber ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IMPORTJOBID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROWNUMBER_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ImportJobItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _importJobItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setImportJobItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _importJobItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ImportJobItem.class;
	}

	@Override
	public String getModelClassName() {
		return ImportJobItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ImportJobItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ImportJobItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ImportJobItem, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ImportJobItem)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ImportJobItem, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ImportJobItem, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ImportJobItem)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ImportJobItem, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ImportJobItem, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ImportJobItem, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ImportJobItem, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ImportJobItem, Object>>();

			attributeGetterFunctions.put(
				"importJobItemId", ImportJobItem::getImportJobItemId);
			attributeGetterFunctions.put("groupId", ImportJobItem::getGroupId);
			attributeGetterFunctions.put(
				"companyId", ImportJobItem::getCompanyId);
			attributeGetterFunctions.put(
				"createDate", ImportJobItem::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ImportJobItem::getModifiedDate);
			attributeGetterFunctions.put(
				"importJobId", ImportJobItem::getImportJobId);
			attributeGetterFunctions.put(
				"rowNumber", ImportJobItem::getRowNumber);
			attributeGetterFunctions.put(
				"articleERC", ImportJobItem::getArticleERC);
			attributeGetterFunctions.put("locale", ImportJobItem::getLocale);
			attributeGetterFunctions.put(
				"operation", ImportJobItem::getOperation);
			attributeGetterFunctions.put("result", ImportJobItem::getResult);
			attributeGetterFunctions.put(
				"severity", ImportJobItem::getSeverity);
			attributeGetterFunctions.put(
				"messageCode", ImportJobItem::getMessageCode);
			attributeGetterFunctions.put("message", ImportJobItem::getMessage);
			attributeGetterFunctions.put(
				"payloadHash", ImportJobItem::getPayloadHash);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ImportJobItem, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ImportJobItem, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<ImportJobItem, ?>>();

			attributeSetterBiConsumers.put(
				"importJobItemId",
				(BiConsumer<ImportJobItem, Long>)
					ImportJobItem::setImportJobItemId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ImportJobItem, Long>)ImportJobItem::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ImportJobItem, Long>)ImportJobItem::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ImportJobItem, Date>)ImportJobItem::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ImportJobItem, Date>)
					ImportJobItem::setModifiedDate);
			attributeSetterBiConsumers.put(
				"importJobId",
				(BiConsumer<ImportJobItem, Long>)ImportJobItem::setImportJobId);
			attributeSetterBiConsumers.put(
				"rowNumber",
				(BiConsumer<ImportJobItem, Integer>)
					ImportJobItem::setRowNumber);
			attributeSetterBiConsumers.put(
				"articleERC",
				(BiConsumer<ImportJobItem, String>)
					ImportJobItem::setArticleERC);
			attributeSetterBiConsumers.put(
				"locale",
				(BiConsumer<ImportJobItem, String>)ImportJobItem::setLocale);
			attributeSetterBiConsumers.put(
				"operation",
				(BiConsumer<ImportJobItem, String>)ImportJobItem::setOperation);
			attributeSetterBiConsumers.put(
				"result",
				(BiConsumer<ImportJobItem, String>)ImportJobItem::setResult);
			attributeSetterBiConsumers.put(
				"severity",
				(BiConsumer<ImportJobItem, String>)ImportJobItem::setSeverity);
			attributeSetterBiConsumers.put(
				"messageCode",
				(BiConsumer<ImportJobItem, String>)
					ImportJobItem::setMessageCode);
			attributeSetterBiConsumers.put(
				"message",
				(BiConsumer<ImportJobItem, String>)ImportJobItem::setMessage);
			attributeSetterBiConsumers.put(
				"payloadHash",
				(BiConsumer<ImportJobItem, String>)
					ImportJobItem::setPayloadHash);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getImportJobItemId() {
		return _importJobItemId;
	}

	@Override
	public void setImportJobItemId(long importJobItemId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importJobItemId = importJobItemId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getImportJobId() {
		return _importJobId;
	}

	@Override
	public void setImportJobId(long importJobId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importJobId = importJobId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalImportJobId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("importJobId"));
	}

	@Override
	public int getRowNumber() {
		return _rowNumber;
	}

	@Override
	public void setRowNumber(int rowNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rowNumber = rowNumber;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalRowNumber() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("rowNumber"));
	}

	@Override
	public String getArticleERC() {
		if (_articleERC == null) {
			return "";
		}
		else {
			return _articleERC;
		}
	}

	@Override
	public void setArticleERC(String articleERC) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_articleERC = articleERC;
	}

	@Override
	public String getLocale() {
		if (_locale == null) {
			return "";
		}
		else {
			return _locale;
		}
	}

	@Override
	public void setLocale(String locale) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locale = locale;
	}

	@Override
	public String getOperation() {
		if (_operation == null) {
			return "";
		}
		else {
			return _operation;
		}
	}

	@Override
	public void setOperation(String operation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_operation = operation;
	}

	@Override
	public String getResult() {
		if (_result == null) {
			return "";
		}
		else {
			return _result;
		}
	}

	@Override
	public void setResult(String result) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_result = result;
	}

	@Override
	public String getSeverity() {
		if (_severity == null) {
			return "";
		}
		else {
			return _severity;
		}
	}

	@Override
	public void setSeverity(String severity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_severity = severity;
	}

	@Override
	public String getMessageCode() {
		if (_messageCode == null) {
			return "";
		}
		else {
			return _messageCode;
		}
	}

	@Override
	public void setMessageCode(String messageCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_messageCode = messageCode;
	}

	@Override
	public String getMessage() {
		if (_message == null) {
			return "";
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_message = message;
	}

	@Override
	public String getPayloadHash() {
		if (_payloadHash == null) {
			return "";
		}
		else {
			return _payloadHash;
		}
	}

	@Override
	public void setPayloadHash(String payloadHash) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_payloadHash = payloadHash;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ImportJobItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ImportJobItem toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ImportJobItem>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ImportJobItemImpl importJobItemImpl = new ImportJobItemImpl();

		importJobItemImpl.setImportJobItemId(getImportJobItemId());
		importJobItemImpl.setGroupId(getGroupId());
		importJobItemImpl.setCompanyId(getCompanyId());
		importJobItemImpl.setCreateDate(getCreateDate());
		importJobItemImpl.setModifiedDate(getModifiedDate());
		importJobItemImpl.setImportJobId(getImportJobId());
		importJobItemImpl.setRowNumber(getRowNumber());
		importJobItemImpl.setArticleERC(getArticleERC());
		importJobItemImpl.setLocale(getLocale());
		importJobItemImpl.setOperation(getOperation());
		importJobItemImpl.setResult(getResult());
		importJobItemImpl.setSeverity(getSeverity());
		importJobItemImpl.setMessageCode(getMessageCode());
		importJobItemImpl.setMessage(getMessage());
		importJobItemImpl.setPayloadHash(getPayloadHash());

		importJobItemImpl.resetOriginalValues();

		return importJobItemImpl;
	}

	@Override
	public ImportJobItem cloneWithOriginalValues() {
		ImportJobItemImpl importJobItemImpl = new ImportJobItemImpl();

		importJobItemImpl.setImportJobItemId(
			this.<Long>getColumnOriginalValue("importJobItemId"));
		importJobItemImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		importJobItemImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		importJobItemImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		importJobItemImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		importJobItemImpl.setImportJobId(
			this.<Long>getColumnOriginalValue("importJobId"));
		importJobItemImpl.setRowNumber(
			this.<Integer>getColumnOriginalValue("rowNumber"));
		importJobItemImpl.setArticleERC(
			this.<String>getColumnOriginalValue("articleERC"));
		importJobItemImpl.setLocale(
			this.<String>getColumnOriginalValue("locale"));
		importJobItemImpl.setOperation(
			this.<String>getColumnOriginalValue("operation"));
		importJobItemImpl.setResult(
			this.<String>getColumnOriginalValue("result"));
		importJobItemImpl.setSeverity(
			this.<String>getColumnOriginalValue("severity"));
		importJobItemImpl.setMessageCode(
			this.<String>getColumnOriginalValue("messageCode"));
		importJobItemImpl.setMessage(
			this.<String>getColumnOriginalValue("message"));
		importJobItemImpl.setPayloadHash(
			this.<String>getColumnOriginalValue("payloadHash"));

		return importJobItemImpl;
	}

	@Override
	public int compareTo(ImportJobItem importJobItem) {
		int value = 0;

		if (getRowNumber() < importJobItem.getRowNumber()) {
			value = -1;
		}
		else if (getRowNumber() > importJobItem.getRowNumber()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ImportJobItem)) {
			return false;
		}

		ImportJobItem importJobItem = (ImportJobItem)object;

		long primaryKey = importJobItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ImportJobItem> toCacheModel() {
		ImportJobItemCacheModel importJobItemCacheModel =
			new ImportJobItemCacheModel();

		importJobItemCacheModel.importJobItemId = getImportJobItemId();

		importJobItemCacheModel.groupId = getGroupId();

		importJobItemCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			importJobItemCacheModel.createDate = createDate.getTime();
		}
		else {
			importJobItemCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			importJobItemCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			importJobItemCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		importJobItemCacheModel.importJobId = getImportJobId();

		importJobItemCacheModel.rowNumber = getRowNumber();

		importJobItemCacheModel.articleERC = getArticleERC();

		String articleERC = importJobItemCacheModel.articleERC;

		if ((articleERC != null) && (articleERC.length() == 0)) {
			importJobItemCacheModel.articleERC = null;
		}

		importJobItemCacheModel.locale = getLocale();

		String locale = importJobItemCacheModel.locale;

		if ((locale != null) && (locale.length() == 0)) {
			importJobItemCacheModel.locale = null;
		}

		importJobItemCacheModel.operation = getOperation();

		String operation = importJobItemCacheModel.operation;

		if ((operation != null) && (operation.length() == 0)) {
			importJobItemCacheModel.operation = null;
		}

		importJobItemCacheModel.result = getResult();

		String result = importJobItemCacheModel.result;

		if ((result != null) && (result.length() == 0)) {
			importJobItemCacheModel.result = null;
		}

		importJobItemCacheModel.severity = getSeverity();

		String severity = importJobItemCacheModel.severity;

		if ((severity != null) && (severity.length() == 0)) {
			importJobItemCacheModel.severity = null;
		}

		importJobItemCacheModel.messageCode = getMessageCode();

		String messageCode = importJobItemCacheModel.messageCode;

		if ((messageCode != null) && (messageCode.length() == 0)) {
			importJobItemCacheModel.messageCode = null;
		}

		importJobItemCacheModel.message = getMessage();

		String message = importJobItemCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			importJobItemCacheModel.message = null;
		}

		importJobItemCacheModel.payloadHash = getPayloadHash();

		String payloadHash = importJobItemCacheModel.payloadHash;

		if ((payloadHash != null) && (payloadHash.length() == 0)) {
			importJobItemCacheModel.payloadHash = null;
		}

		return importJobItemCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ImportJobItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ImportJobItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ImportJobItem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ImportJobItem)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ImportJobItem>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ImportJobItem.class, ModelWrapper.class);

	}

	private long _importJobItemId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _importJobId;
	private int _rowNumber;
	private String _articleERC;
	private String _locale;
	private String _operation;
	private String _result;
	private String _severity;
	private String _messageCode;
	private String _message;
	private String _payloadHash;

	public <T> T getColumnValue(String columnName) {
		Function<ImportJobItem, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ImportJobItem)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("importJobItemId", _importJobItemId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("importJobId", _importJobId);
		_columnOriginalValues.put("rowNumber", _rowNumber);
		_columnOriginalValues.put("articleERC", _articleERC);
		_columnOriginalValues.put("locale", _locale);
		_columnOriginalValues.put("operation", _operation);
		_columnOriginalValues.put("result", _result);
		_columnOriginalValues.put("severity", _severity);
		_columnOriginalValues.put("messageCode", _messageCode);
		_columnOriginalValues.put("message", _message);
		_columnOriginalValues.put("payloadHash", _payloadHash);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("importJobItemId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("importJobId", 32L);

		columnBitmasks.put("rowNumber", 64L);

		columnBitmasks.put("articleERC", 128L);

		columnBitmasks.put("locale", 256L);

		columnBitmasks.put("operation", 512L);

		columnBitmasks.put("result", 1024L);

		columnBitmasks.put("severity", 2048L);

		columnBitmasks.put("messageCode", 4096L);

		columnBitmasks.put("message", 8192L);

		columnBitmasks.put("payloadHash", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ImportJobItem _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-2147099061