/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ArticleImportState service. Represents a row in the &quot;NXC_ArticleImportState&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nexcent.training.model.impl.ArticleImportStateModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nexcent.training.model.impl.ArticleImportStateImpl</code>.
 * </p>
 *
 * @author Nexcent Training
 * @see ArticleImportState
 * @generated
 */
@ProviderType
public interface ArticleImportStateModel
	extends BaseModel<ArticleImportState>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a article import state model instance should use the {@link ArticleImportState} interface instead.
	 */

	/**
	 * Returns the primary key of this article import state.
	 *
	 * @return the primary key of this article import state
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this article import state.
	 *
	 * @param primaryKey the primary key of this article import state
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the article import state ID of this article import state.
	 *
	 * @return the article import state ID of this article import state
	 */
	public long getArticleImportStateId();

	/**
	 * Sets the article import state ID of this article import state.
	 *
	 * @param articleImportStateId the article import state ID of this article import state
	 */
	public void setArticleImportStateId(long articleImportStateId);

	/**
	 * Returns the group ID of this article import state.
	 *
	 * @return the group ID of this article import state
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this article import state.
	 *
	 * @param groupId the group ID of this article import state
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this article import state.
	 *
	 * @return the company ID of this article import state
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this article import state.
	 *
	 * @param companyId the company ID of this article import state
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this article import state.
	 *
	 * @return the create date of this article import state
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this article import state.
	 *
	 * @param createDate the create date of this article import state
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this article import state.
	 *
	 * @return the modified date of this article import state
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this article import state.
	 *
	 * @param modifiedDate the modified date of this article import state
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the article erc of this article import state.
	 *
	 * @return the article erc of this article import state
	 */
	@AutoEscape
	public String getArticleERC();

	/**
	 * Sets the article erc of this article import state.
	 *
	 * @param articleERC the article erc of this article import state
	 */
	public void setArticleERC(String articleERC);

	/**
	 * Returns the locale of this article import state.
	 *
	 * @return the locale of this article import state
	 */
	@AutoEscape
	public String getLocale();

	/**
	 * Sets the locale of this article import state.
	 *
	 * @param locale the locale of this article import state
	 */
	public void setLocale(String locale);

	/**
	 * Returns the payload hash of this article import state.
	 *
	 * @return the payload hash of this article import state
	 */
	@AutoEscape
	public String getPayloadHash();

	/**
	 * Sets the payload hash of this article import state.
	 *
	 * @param payloadHash the payload hash of this article import state
	 */
	public void setPayloadHash(String payloadHash);

	/**
	 * Returns the last import job ID of this article import state.
	 *
	 * @return the last import job ID of this article import state
	 */
	public long getLastImportJobId();

	/**
	 * Sets the last import job ID of this article import state.
	 *
	 * @param lastImportJobId the last import job ID of this article import state
	 */
	public void setLastImportJobId(long lastImportJobId);

	@Override
	public ArticleImportState cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-998406892