/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ImportJobItem service. Represents a row in the &quot;NXC_ImportJobItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nexcent.training.model.impl.ImportJobItemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nexcent.training.model.impl.ImportJobItemImpl</code>.
 * </p>
 *
 * @author Nexcent Training
 * @see ImportJobItem
 * @generated
 */
@ProviderType
public interface ImportJobItemModel
	extends BaseModel<ImportJobItem>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a import job item model instance should use the {@link ImportJobItem} interface instead.
	 */

	/**
	 * Returns the primary key of this import job item.
	 *
	 * @return the primary key of this import job item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this import job item.
	 *
	 * @param primaryKey the primary key of this import job item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the import job item ID of this import job item.
	 *
	 * @return the import job item ID of this import job item
	 */
	public long getImportJobItemId();

	/**
	 * Sets the import job item ID of this import job item.
	 *
	 * @param importJobItemId the import job item ID of this import job item
	 */
	public void setImportJobItemId(long importJobItemId);

	/**
	 * Returns the group ID of this import job item.
	 *
	 * @return the group ID of this import job item
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this import job item.
	 *
	 * @param groupId the group ID of this import job item
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this import job item.
	 *
	 * @return the company ID of this import job item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this import job item.
	 *
	 * @param companyId the company ID of this import job item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this import job item.
	 *
	 * @return the create date of this import job item
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this import job item.
	 *
	 * @param createDate the create date of this import job item
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this import job item.
	 *
	 * @return the modified date of this import job item
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this import job item.
	 *
	 * @param modifiedDate the modified date of this import job item
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the import job ID of this import job item.
	 *
	 * @return the import job ID of this import job item
	 */
	public long getImportJobId();

	/**
	 * Sets the import job ID of this import job item.
	 *
	 * @param importJobId the import job ID of this import job item
	 */
	public void setImportJobId(long importJobId);

	/**
	 * Returns the row number of this import job item.
	 *
	 * @return the row number of this import job item
	 */
	public int getRowNumber();

	/**
	 * Sets the row number of this import job item.
	 *
	 * @param rowNumber the row number of this import job item
	 */
	public void setRowNumber(int rowNumber);

	/**
	 * Returns the article erc of this import job item.
	 *
	 * @return the article erc of this import job item
	 */
	@AutoEscape
	public String getArticleERC();

	/**
	 * Sets the article erc of this import job item.
	 *
	 * @param articleERC the article erc of this import job item
	 */
	public void setArticleERC(String articleERC);

	/**
	 * Returns the locale of this import job item.
	 *
	 * @return the locale of this import job item
	 */
	@AutoEscape
	public String getLocale();

	/**
	 * Sets the locale of this import job item.
	 *
	 * @param locale the locale of this import job item
	 */
	public void setLocale(String locale);

	/**
	 * Returns the operation of this import job item.
	 *
	 * @return the operation of this import job item
	 */
	@AutoEscape
	public String getOperation();

	/**
	 * Sets the operation of this import job item.
	 *
	 * @param operation the operation of this import job item
	 */
	public void setOperation(String operation);

	/**
	 * Returns the result of this import job item.
	 *
	 * @return the result of this import job item
	 */
	@AutoEscape
	public String getResult();

	/**
	 * Sets the result of this import job item.
	 *
	 * @param result the result of this import job item
	 */
	public void setResult(String result);

	/**
	 * Returns the severity of this import job item.
	 *
	 * @return the severity of this import job item
	 */
	@AutoEscape
	public String getSeverity();

	/**
	 * Sets the severity of this import job item.
	 *
	 * @param severity the severity of this import job item
	 */
	public void setSeverity(String severity);

	/**
	 * Returns the message code of this import job item.
	 *
	 * @return the message code of this import job item
	 */
	@AutoEscape
	public String getMessageCode();

	/**
	 * Sets the message code of this import job item.
	 *
	 * @param messageCode the message code of this import job item
	 */
	public void setMessageCode(String messageCode);

	/**
	 * Returns the message of this import job item.
	 *
	 * @return the message of this import job item
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this import job item.
	 *
	 * @param message the message of this import job item
	 */
	public void setMessage(String message);

	/**
	 * Returns the payload hash of this import job item.
	 *
	 * @return the payload hash of this import job item
	 */
	@AutoEscape
	public String getPayloadHash();

	/**
	 * Sets the payload hash of this import job item.
	 *
	 * @param payloadHash the payload hash of this import job item
	 */
	public void setPayloadHash(String payloadHash);

	@Override
	public ImportJobItem cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1045828315