/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ImportJob service. Represents a row in the &quot;NXC_ImportJob&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nexcent.training.model.impl.ImportJobModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nexcent.training.model.impl.ImportJobImpl</code>.
 * </p>
 *
 * @author Nexcent Training
 * @see ImportJob
 * @generated
 */
@ProviderType
public interface ImportJobModel
	extends BaseModel<ImportJob>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a import job model instance should use the {@link ImportJob} interface instead.
	 */

	/**
	 * Returns the primary key of this import job.
	 *
	 * @return the primary key of this import job
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this import job.
	 *
	 * @param primaryKey the primary key of this import job
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this import job.
	 *
	 * @return the uuid of this import job
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this import job.
	 *
	 * @param uuid the uuid of this import job
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the import job ID of this import job.
	 *
	 * @return the import job ID of this import job
	 */
	public long getImportJobId();

	/**
	 * Sets the import job ID of this import job.
	 *
	 * @param importJobId the import job ID of this import job
	 */
	public void setImportJobId(long importJobId);

	/**
	 * Returns the group ID of this import job.
	 *
	 * @return the group ID of this import job
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this import job.
	 *
	 * @param groupId the group ID of this import job
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this import job.
	 *
	 * @return the company ID of this import job
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this import job.
	 *
	 * @param companyId the company ID of this import job
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this import job.
	 *
	 * @return the user ID of this import job
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this import job.
	 *
	 * @param userId the user ID of this import job
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this import job.
	 *
	 * @return the user uuid of this import job
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this import job.
	 *
	 * @param userUuid the user uuid of this import job
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this import job.
	 *
	 * @return the user name of this import job
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this import job.
	 *
	 * @param userName the user name of this import job
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this import job.
	 *
	 * @return the create date of this import job
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this import job.
	 *
	 * @param createDate the create date of this import job
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this import job.
	 *
	 * @return the modified date of this import job
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this import job.
	 *
	 * @param modifiedDate the modified date of this import job
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the job key of this import job.
	 *
	 * @return the job key of this import job
	 */
	@AutoEscape
	public String getJobKey();

	/**
	 * Sets the job key of this import job.
	 *
	 * @param jobKey the job key of this import job
	 */
	public void setJobKey(String jobKey);

	/**
	 * Returns the file entry ID of this import job.
	 *
	 * @return the file entry ID of this import job
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this import job.
	 *
	 * @param fileEntryId the file entry ID of this import job
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the file name of this import job.
	 *
	 * @return the file name of this import job
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this import job.
	 *
	 * @param fileName the file name of this import job
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the sha256 of this import job.
	 *
	 * @return the sha256 of this import job
	 */
	@AutoEscape
	public String getSha256();

	/**
	 * Sets the sha256 of this import job.
	 *
	 * @param sha256 the sha256 of this import job
	 */
	public void setSha256(String sha256);

	/**
	 * Returns the import profile key of this import job.
	 *
	 * @return the import profile key of this import job
	 */
	@AutoEscape
	public String getImportProfileKey();

	/**
	 * Sets the import profile key of this import job.
	 *
	 * @param importProfileKey the import profile key of this import job
	 */
	public void setImportProfileKey(String importProfileKey);

	/**
	 * Returns the package schema version of this import job.
	 *
	 * @return the package schema version of this import job
	 */
	@AutoEscape
	public String getPackageSchemaVersion();

	/**
	 * Sets the package schema version of this import job.
	 *
	 * @param packageSchemaVersion the package schema version of this import job
	 */
	public void setPackageSchemaVersion(String packageSchemaVersion);

	/**
	 * Returns the structure erc of this import job.
	 *
	 * @return the structure erc of this import job
	 */
	@AutoEscape
	public String getStructureERC();

	/**
	 * Sets the structure erc of this import job.
	 *
	 * @param structureERC the structure erc of this import job
	 */
	public void setStructureERC(String structureERC);

	/**
	 * Returns the status of this import job.
	 *
	 * @return the status of this import job
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this import job.
	 *
	 * @param status the status of this import job
	 */
	public void setStatus(String status);

	/**
	 * Returns the total rows of this import job.
	 *
	 * @return the total rows of this import job
	 */
	public int getTotalRows();

	/**
	 * Sets the total rows of this import job.
	 *
	 * @param totalRows the total rows of this import job
	 */
	public void setTotalRows(int totalRows);

	/**
	 * Returns the created rows of this import job.
	 *
	 * @return the created rows of this import job
	 */
	public int getCreatedRows();

	/**
	 * Sets the created rows of this import job.
	 *
	 * @param createdRows the created rows of this import job
	 */
	public void setCreatedRows(int createdRows);

	/**
	 * Returns the updated rows of this import job.
	 *
	 * @return the updated rows of this import job
	 */
	public int getUpdatedRows();

	/**
	 * Sets the updated rows of this import job.
	 *
	 * @param updatedRows the updated rows of this import job
	 */
	public void setUpdatedRows(int updatedRows);

	/**
	 * Returns the skipped rows of this import job.
	 *
	 * @return the skipped rows of this import job
	 */
	public int getSkippedRows();

	/**
	 * Sets the skipped rows of this import job.
	 *
	 * @param skippedRows the skipped rows of this import job
	 */
	public void setSkippedRows(int skippedRows);

	/**
	 * Returns the failed rows of this import job.
	 *
	 * @return the failed rows of this import job
	 */
	public int getFailedRows();

	/**
	 * Sets the failed rows of this import job.
	 *
	 * @param failedRows the failed rows of this import job
	 */
	public void setFailedRows(int failedRows);

	/**
	 * Returns the started date of this import job.
	 *
	 * @return the started date of this import job
	 */
	public Date getStartedDate();

	/**
	 * Sets the started date of this import job.
	 *
	 * @param startedDate the started date of this import job
	 */
	public void setStartedDate(Date startedDate);

	/**
	 * Returns the completed date of this import job.
	 *
	 * @return the completed date of this import job
	 */
	public Date getCompletedDate();

	/**
	 * Sets the completed date of this import job.
	 *
	 * @param completedDate the completed date of this import job
	 */
	public void setCompletedDate(Date completedDate);

	/**
	 * Returns the error message of this import job.
	 *
	 * @return the error message of this import job
	 */
	@AutoEscape
	public String getErrorMessage();

	/**
	 * Sets the error message of this import job.
	 *
	 * @param errorMessage the error message of this import job
	 */
	public void setErrorMessage(String errorMessage);

	@Override
	public ImportJob cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-766024709