#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=com.nexcent.training.rest.dto.v1_0.ArticleImportJob
batch.engine.task.item.delegate=true
batch.planner.export.enabled=true
batch.planner.import.enabled=true
entity.class.name=com.nexcent.training.rest.dto.v1_0.ArticleImportJob
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Nexcent.Training)
osgi.jaxrs.resource=true