#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/nexcent-training
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Nexcent.Training)
osgi.jaxrs.resource=true