#
# MySQL
#
#jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
#jdbc.default.url=jdbc:mysql://localhost/lportal
#jdbc.default.username=root
#jdbc.default.password=

#
# Nexcent local training environment
#

include-and-override=portal-developer.properties

browser.launcher.url=

#
# Default company
#

company.default.name=Nexcent
company.default.web.id=nexcent.com
company.security.auth.type=emailAddress
company.security.strangers=false

#
# Default administrator
#

default.admin.email.address.prefix=admin
default.admin.first.name=Nexcent
default.admin.last.name=Admin
default.admin.password=learn
default.admin.screen.name=nexcentadmin

#
# Course conveniences
#

passwords.default.policy.change.required=false
terms.of.use.required=false
users.reminder.queries.enabled=false
users.reminder.queries.custom.question.enabled=false