apiDir: "../nexcent-site-shell-rest-api/src/main/java"
apiPackagePath: "com.nexcent.site.shell.rest"
application:
    baseURI: "/nexcent-site-shell"
    className: "NexcentSiteShellApplication"
    name: "Liferay.Nexcent.Site.Shell"
author: "Nexcent"
javaEEPackage: "jakarta"
